### PR TITLE
4th project completed

### PR DESCRIPTION
**Pull request by angel-mora**
6th attempt as unable to fix sticklers errors.
This is Microverse 4th project Apple clone completed and reviewed.
HTML and CSS validators checked.
Struggled a bit with stickler files and permissions but all fixed now.
About scrolling sideways, I don't think there's an issue. I added overflow-x:hidden to the wrapper container but it is still scrolling sideways. I think this is not a responsive site yet so I don't know why it is important if bar appears when about to reach ipad size and it is not giving any issue with regular monitors (I tried 1320 and 1920 width screens)
# TSE comments addressed.

### CODE REVIEW

**Comment by kobiyoyo** [comment]
## Pull Request under review, by Adama Chubiyojo Desmond (TSE)

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @angel-mora       
#### Great Job so far, but there are a few more things required. 
### General
- [ ] Your Pull Request should have a short description ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload
- [ ]  it's scrolling sideways, let's fix that.

### Bottom
- [ ] This four elements should be links

#### Implementation details

* [ ] Elements should be aligned with [float](https://css-tricks.com/all-about-floats/) and [flex](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) or [grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/align_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

### Make changes and submit another code review request.
*Happy coding*

**Review by pelzolga123 — APPROVED** [review]
Approved.

**Comment by pelzolga123** [comment]
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

**Pull request merged**
